image: node:latest

stages:
        - test
        - production

test:
        stage: test
        script:
                - npm install
                - npm run test

production:
        type: deploy
        stage: production
        image: ruby:latest
        script:
                - apt-get update -qy
                - apt-get install -y ruby-dev
                - gem install dpl
                - dpl --provider=heroku --app=ramshue --api-key=$HEROKU_API_KEY 
        only:
                - master
